apiVersion: v1
kind: ConfigMap
metadata:
  name: releaselogs-config
  labels:
    app.kubernetes.io/name: releaselogs
    app.kubernetes.io/component: web
data:
  config.yaml: |
    elasticsearch:
      nodeUrls: https://elasticsearch:9200
      authMethod: basic
      username: elastic
      password: super-secure-production-elastic-key
      token: ''
      enableSSL: true
      verifyServerCertificate: true
      caCertificateName: releaselogs-local-ca.crt
      caCertificateContent: |-
        -----BEGIN CERTIFICATE-----
        MIIFHzCCAwegAwIBAgIUY06DeSSXljFm2uH/0X5AQVFSNe0wDQYJKoZIhvcNAQEL
        BQAwHzEdMBsGA1UEAwwUcmVsZWFzZWxvZ3MtbG9jYWwtY2EwHhcNMjYwNTI5MDMy
        MzE1WhcNMzYwNTI2MDMyMzE1WjAfMR0wGwYDVQQDDBRyZWxlYXNlbG9ncy1sb2Nh
        bC1jYTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAORW1qx9Nyp4Hv5k
        BTqxtfJ94ts6CkRCrBBckzs2NOjAThZui5XzCo75PnrGh4oMEfQXJ+k7KPd7DZtA
        BYc6O71jNH4hS/K3FlmndBrk3Lo32Q9h0KTNxIyi+7lSXTIqDIehPCacb3lgyRB3
        u1zxMzRQ3C1zl2Csum7jpQiwpDCnN0X6iMsdJa/7orblJatjMslvPRPAdsAqsWpE
        EzRQXIz4ekrJ6r3Z+FNYLJe5uufzHZheGzX+1IDrw15wWxuVsiqvcLP9Scnv3szQ
        X7oe+HHHTkaax7o7QpmntY93isnXQBqukkKZG+GUWjT5OeypzSQcGFcW6jOuPY0Q
        149yob6VqwDNLivlvAxGMvEDxihWaDNg9QunTz1PLLlfFAWfZPVkPNT6kMJ6LKZ2
        NE/TME8pV749Ey/QbK2zftRvm3GzbGgpK81ZSjVDCkT3Toeo7QrgAFCANLFDJPn1
        kMzA0LkOj+LAsb/N3ZuA0w7cRaQqonHY0/nkJcmpcCQUhA2O12idZNg/nzUauVDt
        F5s7bKAh4HwPdJ4AmLvswlC60PUN/1a4+CwGyhVsFdy4dgDiXHqULNOgK21azHDy
        wiPA5NvlLFoaIRjbGyo4ioTzDSB7Iy9Tu4RiUMQ+qasPZ1e7+RpwgZnwYlLIVrOh
        9+hrrQv86vxjicB8RMFzoPENOLTXAgMBAAGjUzBRMB0GA1UdDgQWBBTVQkxTSiwD
        qrYB44CdbirObpj2PjAfBgNVHSMEGDAWgBTVQkxTSiwDqrYB44CdbirObpj2PjAP
        BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQCp3frkPYzzb3U1d77B
        caIT06paWbEw+PBKiMnZBv7bwb6bJB+1TU2L5hm3k1UQB6pKZ+ATQ8HiT+yWfNZS
        HNQFKcwZs8/mi0lZt80ItiJy3NzLp88wuTc36f1PPbzO2qtCGkC6rCbU7fl+Ojcw
        bpGVg84XwMW/HM2vg4//zIRs++2N8PNJt26NQudtWHXyx6p5Z+rSeJDhLdseka4M
        VN3DTWUZKmMpVuh2Ctp7LOUrFfIqfxc4RauM/bUNo8qY31GUXSw9Wv2VuNG8kHY7
        DKw7WR+kxUOMD31DSOYjp8oiHIDsyuYOshWLiQwySmQh0fPD+rshypQkBcbNHjV/
        uE/83EpSDsh/dqkDQAjZcD7EYUu0sphosdlCllGyqkQv/jOhzVIGSButndcsVvim
        HSM1mik1WhW5xKqH5ed94C5K0pe5o+RQ9b8lfLIrfcCFVOzOVVaIpWX8UbZzY054
        E/KZcC/xAo26I++P09trY6J3MgYWMHxgcUASxHww+aL70Av1DvN5pwFvAvAZIQB+
        J8giciVXOvetYrCRcT2Usssyl7re5x4GbGiQqE1TAGjqedHJoXvHwTeMHIl+c+jv
        uBVO2g44xhwel4XnDkzwVa3oHPRylpS04Qes4xGr+pluaQLrXzPcGaE2UhzYcMjl
        NzEvsxThrkE3Ghy4kqxkv565lw==
        -----END CERTIFICATE-----
      clientCertificateName: ''
      clientCertificateContent: ''
      clientKeyName: ''
      clientKeyContent: ''
      clusterName: ''
      shardsCount: 0
      replicasCount: 0
    s3:
      endpointUrl: https://minio:9000
      accessKeyId: minioadmin
      secretAccessKey: minioadmin
      bucketName: elastic-kibana-logs
      region: us-east-1
      enableSSL: true
      verifyCertificates: true
      caCertificateName: releaselogs-local-ca.crt
      caCertificateContent: |-
        -----BEGIN CERTIFICATE-----
        MIIFHzCCAwegAwIBAgIUY06DeSSXljFm2uH/0X5AQVFSNe0wDQYJKoZIhvcNAQEL
        BQAwHzEdMBsGA1UEAwwUcmVsZWFzZWxvZ3MtbG9jYWwtY2EwHhcNMjYwNTI5MDMy
        MzE1WhcNMzYwNTI2MDMyMzE1WjAfMR0wGwYDVQQDDBRyZWxlYXNlbG9ncy1sb2Nh
        bC1jYTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBAORW1qx9Nyp4Hv5k
        BTqxtfJ94ts6CkRCrBBckzs2NOjAThZui5XzCo75PnrGh4oMEfQXJ+k7KPd7DZtA
        BYc6O71jNH4hS/K3FlmndBrk3Lo32Q9h0KTNxIyi+7lSXTIqDIehPCacb3lgyRB3
        u1zxMzRQ3C1zl2Csum7jpQiwpDCnN0X6iMsdJa/7orblJatjMslvPRPAdsAqsWpE
        EzRQXIz4ekrJ6r3Z+FNYLJe5uufzHZheGzX+1IDrw15wWxuVsiqvcLP9Scnv3szQ
        X7oe+HHHTkaax7o7QpmntY93isnXQBqukkKZG+GUWjT5OeypzSQcGFcW6jOuPY0Q
        149yob6VqwDNLivlvAxGMvEDxihWaDNg9QunTz1PLLlfFAWfZPVkPNT6kMJ6LKZ2
        NE/TME8pV749Ey/QbK2zftRvm3GzbGgpK81ZSjVDCkT3Toeo7QrgAFCANLFDJPn1
        kMzA0LkOj+LAsb/N3ZuA0w7cRaQqonHY0/nkJcmpcCQUhA2O12idZNg/nzUauVDt
        F5s7bKAh4HwPdJ4AmLvswlC60PUN/1a4+CwGyhVsFdy4dgDiXHqULNOgK21azHDy
        wiPA5NvlLFoaIRjbGyo4ioTzDSB7Iy9Tu4RiUMQ+qasPZ1e7+RpwgZnwYlLIVrOh
        9+hrrQv86vxjicB8RMFzoPENOLTXAgMBAAGjUzBRMB0GA1UdDgQWBBTVQkxTSiwD
        qrYB44CdbirObpj2PjAfBgNVHSMEGDAWgBTVQkxTSiwDqrYB44CdbirObpj2PjAP
        BgNVHRMBAf8EBTADAQH/MA0GCSqGSIb3DQEBCwUAA4ICAQCp3frkPYzzb3U1d77B
        caIT06paWbEw+PBKiMnZBv7bwb6bJB+1TU2L5hm3k1UQB6pKZ+ATQ8HiT+yWfNZS
        HNQFKcwZs8/mi0lZt80ItiJy3NzLp88wuTc36f1PPbzO2qtCGkC6rCbU7fl+Ojcw
        bpGVg84XwMW/HM2vg4//zIRs++2N8PNJt26NQudtWHXyx6p5Z+rSeJDhLdseka4M
        VN3DTWUZKmMpVuh2Ctp7LOUrFfIqfxc4RauM/bUNo8qY31GUXSw9Wv2VuNG8kHY7
        DKw7WR+kxUOMD31DSOYjp8oiHIDsyuYOshWLiQwySmQh0fPD+rshypQkBcbNHjV/
        uE/83EpSDsh/dqkDQAjZcD7EYUu0sphosdlCllGyqkQv/jOhzVIGSButndcsVvim
        HSM1mik1WhW5xKqH5ed94C5K0pe5o+RQ9b8lfLIrfcCFVOzOVVaIpWX8UbZzY054
        E/KZcC/xAo26I++P09trY6J3MgYWMHxgcUASxHww+aL70Av1DvN5pwFvAvAZIQB+
        J8giciVXOvetYrCRcT2Usssyl7re5x4GbGiQqE1TAGjqedHJoXvHwTeMHIl+c+jv
        uBVO2g44xhwel4XnDkzwVa3oHPRylpS04Qes4xGr+pluaQLrXzPcGaE2UhzYcMjl
        NzEvsxThrkE3Ghy4kqxkv565lw==
        -----END CERTIFICATE-----
      forcePathStyle: true
      catalogIndex: release-logs
    ldap:
      serverUrl: ''
      bindDn: ''
      bindPassword: ''
      baseDn: ''
      userSearchFilter: ''
      groupSearchFilter: ''
      enableSSL: false
      verifyCertificates: false
      caCertificateName: ''
      caCertificateContent: ''
      activeDirectoryMode: false
    audit:
      elasticsearchIndex: audit-logs
    discover:
      defaultIndex: ''
      linkRules:
        - columnName: download_url
          urlTemplate: '{value}'
          labelTemplate: S3 Archive Payload
          openInNewTab: true
          colorScheme: indigo
        - columnName: ip
          urlTemplate: https://ipinfo.io/{value}
          labelTemplate: 'IP lookup: {value}'
          openInNewTab: true
          colorScheme: blue
    app:
      enableHTTPS: false
      httpsPort: 3443
      certificateName: ''
      certificateContent: ''
      privateKeyName: ''
      privateKeyContent: ''
      commonName: ''
      validDays: 0
